package GUI;

import Componentes.Artista;
import Componentes.Cancion;
import Componentes.Catalogo;
import Componentes.Disco;
import Componentes.Exportar;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Francis
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    
    public static ArrayList<Artista> listaArtistas = new ArrayList<Artista>();
    public static ArrayList<Cancion> listaCanciones = new ArrayList<Cancion>();
    public static ArrayList<Disco> listaDiscos = new ArrayList<Disco>();
    ArrayList<String> listaCancionesCatalogo = new ArrayList<String>();
    static ArrayList<Catalogo> listaCatalogos = new ArrayList<Catalogo>();
    
    DefaultComboBoxModel<String> modelArtista = new DefaultComboBoxModel<String>();
    DefaultComboBoxModel<String> modelDisco = new DefaultComboBoxModel<String>();
    
    DefaultListModel<String> modelListaDisco = new DefaultListModel<String>();
    
    DefaultMutableTreeNode root = new DefaultMutableTreeNode("Base de datos", true);
    DefaultMutableTreeNode nodoArtistas = new DefaultMutableTreeNode("Artistas");
    DefaultMutableTreeNode nodoDiscos = new DefaultMutableTreeNode("Discos");
    DefaultMutableTreeNode nodoCanciones = new DefaultMutableTreeNode("Canciones");
    DefaultMutableTreeNode nodoSeleccionado;

    public Home() {
        root.add(nodoArtistas);
        root.add(nodoDiscos);
        root.add(nodoCanciones);
        modelDisco.addElement("Desconocido");
        modelArtista.addElement("Desconocido");
        
        initComponents();
    }
    
    DefaultTreeModel modeloArbol = new DefaultTreeModel(root);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelRoot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        artistField1 = new javax.swing.JTextField();
        dniField = new javax.swing.JTextField();
        nacionalidadField = new javax.swing.JTextField();
        regArtistButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codigoField = new javax.swing.JTextField();
        discoField = new javax.swing.JTextField();
        artistaComboBox1 = new javax.swing.JComboBox<>();
        regDiscoButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        cancionField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        duracionField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        artistaComboBox2 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        regCancionButton = new javax.swing.JButton();
        discoComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        spinStock = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        formatPrecioField = new javax.swing.JFormattedTextField();
        numeroSpiner = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        removerDiscoCatalogo = new javax.swing.JButton();
        genReport = new javax.swing.JButton();
        comCatalogo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        arbolDatos = new javax.swing.JTree();
        jScrollPane1 = new javax.swing.JScrollPane();
        showData = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        nombreCatalogoField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        discoComboBox2 = new javax.swing.JComboBox<>();
        creaCatalogo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDiscosCatalogo = new javax.swing.JList<>();
        agregarDiscoCatalogo = new javax.swing.JButton();
        exportDatos = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        stockCatalogoSpinner = new javax.swing.JSpinner();
        formattedPrecioCatalogo = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanelRoot.setBackground(new java.awt.Color(0, 153, 153));
        JPanelRoot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Artista:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DNI:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nacionalidad:");

        artistField1.setForeground(new java.awt.Color(51, 51, 51));

        regArtistButton.setBackground(new java.awt.Color(51, 51, 51));
        regArtistButton.setForeground(new java.awt.Color(255, 255, 255));
        regArtistButton.setText("Registrar Artista");
        regArtistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regArtistButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Disco:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Artista:");

        artistaComboBox1.setModel(modelArtista);
        artistaComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                artistaComboBox1ActionPerformed(evt);
            }
        });

        regDiscoButton.setBackground(new java.awt.Color(51, 51, 51));
        regDiscoButton.setForeground(new java.awt.Color(255, 255, 255));
        regDiscoButton.setText("Registrar Disco");
        regDiscoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regDiscoButtonActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Canción:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Disco:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Duración:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Artista:");

        artistaComboBox2.setModel(modelArtista);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("N\":");

        regCancionButton.setBackground(new java.awt.Color(51, 51, 51));
        regCancionButton.setForeground(new java.awt.Color(255, 255, 255));
        regCancionButton.setText("Registrar Canción");
        regCancionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regCancionButtonActionPerformed(evt);
            }
        });

        discoComboBox1.setModel(modelDisco);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registrar artista");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Registrar disco");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Registrar canción");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Precio:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Stock");

        formatPrecioField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regDiscoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(formatPrecioField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spinStock, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(discoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(regCancionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(artistField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(regArtistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(nacionalidadField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel15)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(discoField, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(artistaComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(duracionField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cancionField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(artistaComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numeroSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel2))
                    .addComponent(artistField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel3))
                    .addComponent(dniField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel4))
                    .addComponent(nacionalidadField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(regArtistButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(codigoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(discoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(artistaComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(formatPrecioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(spinStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(regDiscoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cancionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(duracionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(numeroSpiner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(artistaComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(discoComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(regCancionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        JPanelRoot.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 390, 770));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Casa de discos \"El Piratin\" ");
        JPanelRoot.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 30));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));

        removerDiscoCatalogo.setBackground(new java.awt.Color(51, 51, 51));
        removerDiscoCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        removerDiscoCatalogo.setText("Remover disco del catálogo");
        removerDiscoCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerDiscoCatalogoActionPerformed(evt);
            }
        });

        genReport.setBackground(new java.awt.Color(51, 51, 51));
        genReport.setForeground(new java.awt.Color(255, 255, 255));
        genReport.setText("Generar reportes");
        genReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genReportActionPerformed(evt);
            }
        });

        comCatalogo.setBackground(new java.awt.Color(51, 51, 51));
        comCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        comCatalogo.setText("Comprar catálogo");
        comCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comCatalogoActionPerformed(evt);
            }
        });

        arbolDatos.setModel(modeloArbol);
        arbolDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arbolDatosMouseClicked(evt);
            }
        });
        arbolDatos.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                arbolDatosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(arbolDatos);

        showData.setEditable(false);
        showData.setColumns(20);
        showData.setRows(5);
        jScrollPane1.setViewportView(showData);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mostrar registros");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Crear catálogo");

        nombreCatalogoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCatalogoFieldActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Nombre catálogo:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Disco:");

        discoComboBox2.setModel(modelDisco);

        creaCatalogo.setBackground(new java.awt.Color(51, 51, 51));
        creaCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        creaCatalogo.setText("Crear catálogo");
        creaCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creaCatalogoActionPerformed(evt);
            }
        });

        listaDiscosCatalogo.setModel(modelListaDisco);
        listaDiscosCatalogo.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaDiscosCatalogo.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaDiscosCatalogoValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listaDiscosCatalogo);

        agregarDiscoCatalogo.setBackground(new java.awt.Color(51, 51, 51));
        agregarDiscoCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        agregarDiscoCatalogo.setText("Agregar disco al catálogo");
        agregarDiscoCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDiscoCatalogoActionPerformed(evt);
            }
        });

        exportDatos.setBackground(new java.awt.Color(51, 51, 51));
        exportDatos.setForeground(new java.awt.Color(255, 255, 255));
        exportDatos.setText("Exportar datos");
        exportDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportDatosActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Precio del catálogo:");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Stock de catálogo:");

        formattedPrecioCatalogo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        formattedPrecioCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedPrecioCatalogoActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Discos del catálogo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel19)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(nombreCatalogoField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(discoComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel24)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(stockCatalogoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel23)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(formattedPrecioCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(comCatalogo)
                                                .addGap(59, 59, 59)
                                                .addComponent(genReport, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(13, 13, 13))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(creaCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregarDiscoCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(exportDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(removerDiscoCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel25)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nombreCatalogoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel25))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19)
                                .addGap(38, 38, 38)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(discoComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(formattedPrecioCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(stockCatalogoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creaCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(agregarDiscoCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removerDiscoCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genReport, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exportDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        JPanelRoot.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 620, 770));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanelRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regCancionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regCancionButtonActionPerformed
        // TODO add your handling code here:

        listaCanciones.add(new Cancion(
                (String)modelArtista.getSelectedItem(),
                (String)modelDisco.getSelectedItem(), 
                (int) numeroSpiner.getValue(), 
                cancionField.getText(), 
                duracionField.getText()
        ));
        
        cancionField.setText("");
        duracionField.setText("");
        numeroSpiner.setValue(0);
        
        // Creación de nodos hijo para el nodo Canciones
        DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(
                listaCanciones.get(listaCanciones.size()-1).getNombreCancion()
        );
        
        modeloArbol.insertNodeInto(
                nodo, 
                nodoCanciones, 
                nodoCanciones.getChildCount()
        );
    }//GEN-LAST:event_regCancionButtonActionPerformed

    private void regDiscoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regDiscoButtonActionPerformed
        // TODO add your handling code here:
        String nombreDisco = discoField.getText();
        
        boolean discoExistente = false;
        for (int i = 0; i<modelDisco.getSize(); i++) {
            if (nombreDisco.equals(modelArtista.getElementAt(i))) {
                discoExistente = true;
                break;
            }
        }
        
        if (!discoExistente) {
            modelDisco.addElement(nombreDisco);
        }
        
        listaDiscos.add(new Disco(
            codigoField.getText(),
            discoField.getText(),
            (String) modelArtista.getSelectedItem(),
            (int) spinStock.getValue(),
            (double) formatPrecioField.getValue()
        ));

        codigoField.setText("");
        discoField.setText("");
        formatPrecioField.setValue(0);
        spinStock.setValue(0);
        
        // Creación de nodos hijo para el nodo Discos
        DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(
                listaDiscos.get(listaDiscos.size()-1).getNombreDisco()
        );
        modeloArbol.insertNodeInto(
                nodo, 
                nodoDiscos, 
                nodoDiscos.getChildCount()
        );
    }//GEN-LAST:event_regDiscoButtonActionPerformed

    private void artistaComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_artistaComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_artistaComboBox1ActionPerformed

    private void regArtistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regArtistButtonActionPerformed
        // TODO add your handling code here:
        String nombreArtista = artistField1.getText();
    
        // Verifica si el nombre del artista ya existe en el modelo
        boolean artistaExistente = false;
        for (int i = 0; i < modelArtista.getSize(); i++) {
            if (nombreArtista.equals(modelArtista.getElementAt(i))) {
                artistaExistente = true;
                break;
            }
        }

        // Si el nombre del artista no existe, agrégalo al modelo
        if (!artistaExistente) {
            modelArtista.addElement(nombreArtista);
        }

        // Agrega el artista a la lista de artistas
        listaArtistas.add(new Artista(
                dniField.getText(), 
                nombreArtista, 
                nacionalidadField.getText()
        ));

        // Limpia los campos de entrada
        artistField1.setText("");
        dniField.setText("");
        nacionalidadField.setText("");

        // Creación de nodos hijo para el nodo Artistas
        DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(
                listaArtistas.get(listaArtistas.size()-1).getNombre()
        );
        modeloArbol.insertNodeInto(
                nodo, 
                nodoArtistas, 
                nodoArtistas.getChildCount()
        );
    }//GEN-LAST:event_regArtistButtonActionPerformed

    private void removerDiscoCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerDiscoCatalogoActionPerformed
        // TODO add your handling code here:
        modelListaDisco.removeElement(listaDiscosCatalogo.getSelectedValue());
    }//GEN-LAST:event_removerDiscoCatalogoActionPerformed

    private void genReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genReportActionPerformed
        // TODO add your handling code here:
        Reporte report = new Reporte(this, true);
        report.setVisible(true);
    }//GEN-LAST:event_genReportActionPerformed

    private void arbolDatosValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_arbolDatosValueChanged
        
        nodoSeleccionado = (DefaultMutableTreeNode) arbolDatos.getLastSelectedPathComponent();
        if (nodoSeleccionado != null) {
            for (Artista art : listaArtistas) {
                if (art.getNombre() == nodoSeleccionado.toString()) {
                    art.agregarDisco(listaDiscos);
                    
                    StringBuilder sb = new StringBuilder();
                    sb.append("[");
                    int totalDiscos = art.getDiscosArtista().size();
                    for (int i = 0; i < totalDiscos; i++) {
                        Disco discoIter = art.getDiscosArtista().get(i);
                        sb.append("\"").append(discoIter.getNombreDisco()).append("\"");
                        if (i < totalDiscos - 1) {
                            sb.append(", ");
                        }
                    }
                    sb.append("]");
                    String discos = sb.toString();
                    
                    System.out.println(sb.toString());

                    showData.setText(String.format(
                        """
                        Nombre: %s
                        DNI: %s
                        Nacionalidad: %s
                        Discos: %s
                        """,
                        art.getNombre(),
                        art.getDni(),
                        art.getNacionalidad(),
                        discos
                        //art.getDiscosArtista().toString()
                    ));
                }
            }
            
            for (Disco disk : listaDiscos) {
                if (disk.getNombreDisco() == nodoSeleccionado.toString()) {
                    disk.agregarCancion(listaCanciones);
                    
                    StringBuilder sb = new StringBuilder();
                    sb.append("[");
                    int totalCanciones = disk.getCancionDisco().size();
                    for (int i = 0; i < totalCanciones; i++) {
                        Cancion cancionIter = disk.getCancionDisco().get(i);
                        sb.append("\"").append(cancionIter.getNombreCancion()).append("\"");
                        if (i < totalCanciones - 1) {
                            sb.append(", ");
                        }
                    }
                    sb.append("]");
                    String canciones = sb.toString();
                    
                    System.out.println(sb.toString());
                    showData.setText(String.format(
                        """
                        Disco: %s
                        Código: %s
                        Artista: %s
                        Precio: %.2f
                        Stock: %d
                        Canciones: %s
                        """,
                        disk.getNombreDisco(),
                        disk.getCodigoDisco(),
                        disk.getArtistaDisco(),
                        disk.getPrecio(),
                        disk.getStock(),
                        canciones
                        //disk.getCancionDisco()
                    
                    ));
                }
            }
            for (Cancion can : listaCanciones) {
                if (can.getNombreCancion() == nodoSeleccionado.toString()) {
                    showData.setText(String.format(
                        """
                        Canción: %s
                        Artista: %s
                        Duración: %s
                        N°: %s
                        Disco: %s
                        """,
                        can.getNombreCancion(),
                        can.getNombreArtista(),
                        can.getTiempoCancion(),
                        can.getNumeroCancion(),
                        can.getNombreDisco()
                    ));
                }
            }
            
            
            System.out.println(nodoSeleccionado);
        } 
    }//GEN-LAST:event_arbolDatosValueChanged

    private void nombreCatalogoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCatalogoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCatalogoFieldActionPerformed

    private void comCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comCatalogoActionPerformed
        // TODO add your handling code here:
        Comprar comprarCtalogo = new Comprar(this, true, listaCatalogos);
        comprarCtalogo.setVisible(true);
    }//GEN-LAST:event_comCatalogoActionPerformed

    private void agregarDiscoCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDiscoCatalogoActionPerformed
        // TODO add your handling code here:
        
        if (modelListaDisco.contains(modelDisco.getSelectedItem().toString())) {
            System.out.println("El disco ya se encuentra en el catalogo");
        }
        
        else {
            modelListaDisco.addElement(modelDisco.getSelectedItem().toString());
        }
    }//GEN-LAST:event_agregarDiscoCatalogoActionPerformed

    private void exportDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportDatosActionPerformed
        try {                                            
            // TODO add your handling code here:
            Exportar datos = new Exportar();
            datos.crearArchivo("Artistas.txt");
            datos.crearArchivo("Canciones.txt");
            datos.crearArchivo("Discos.txt");
            datos.crearArchivo("Venta.txt");
            
            try (FileWriter escribirArtistas = new FileWriter("Artistas.txt", true);
                    FileWriter escribirCanciones = new FileWriter("Canciones.txt", true);
                    FileWriter escribirDiscos = new FileWriter("Discos.txt", true);
                    FileWriter escribirVenta = new FileWriter("Venta.txt", true)) {
                
                for (Artista artist : listaArtistas) {
                    if(artist != null) {
                        escribirArtistas.write("------------------------------------------------\n");
                        escribirArtistas.write("Nombre: " + artist.getNombre() + "\n");
                        escribirArtistas.write("DNI: " + artist.getDni() + "\n");
                        escribirArtistas.write("Nacionalidad: " + artist.getNacionalidad() + "\n");
                        escribirArtistas.write("------------------------------------------------\n");
                    }
                }
                
                for (Cancion music : listaCanciones) {
                    if(music != null) {
                        escribirCanciones.write("------------------------------------------------\n");
                        escribirCanciones.write("Canción: " + music.getNombreCancion() + "\n");
                        escribirCanciones.write("Artista: " + music.getNombreArtista() + "\n");
                        escribirCanciones.write("Disco: " + music.getNombreDisco() + "\n");
                        escribirCanciones.write("Duración: " + music.getTiempoCancion() + "\n");
                        escribirCanciones.write("N°: " + music.getNumeroCancion() + "\n");
                        escribirCanciones.write("------------------------------------------------\n");
                    }
                }
                
                for (Disco disk : listaDiscos) {
                    if(disk != null) {
                        escribirDiscos.write("------------------------------------------------\n");
                        escribirDiscos.write("Código: " + disk.getCodigoDisco() + "\n");
                        escribirDiscos.write("Disco: " + disk.getNombreDisco() + "\n");
                        escribirDiscos.write("Artista: " + disk.getArtistaDisco() + "\n");
                        escribirDiscos.write("------------------------------------------------\n");
                    }
                }
                
                System.out.println("Los datos se exportaron correctamente");
                
            }        } catch (IOException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_exportDatosActionPerformed

    private void creaCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creaCatalogoActionPerformed
        // TODO add your handling code here:
        listaCatalogos.add(new Catalogo(
                nombreCatalogoField.getText(),
                (double) formattedPrecioCatalogo.getValue(),
                (int) stockCatalogoSpinner.getValue()
        ));
        
        nombreCatalogoField.setText("");
        formattedPrecioCatalogo.setValue(0);
        stockCatalogoSpinner.setValue(0);
        
        modelListaDisco.clear();
        
    }//GEN-LAST:event_creaCatalogoActionPerformed

    private void arbolDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arbolDatosMouseClicked
        // TODO add your handling code here:        
    }//GEN-LAST:event_arbolDatosMouseClicked

    private void listaDiscosCatalogoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaDiscosCatalogoValueChanged
        // TODO add your handling code here: 
    }//GEN-LAST:event_listaDiscosCatalogoValueChanged

    private void formattedPrecioCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedPrecioCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedPrecioCatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelRoot;
    private javax.swing.JButton agregarDiscoCatalogo;
    private javax.swing.JTree arbolDatos;
    private javax.swing.JTextField artistField1;
    private javax.swing.JComboBox<String> artistaComboBox1;
    private javax.swing.JComboBox<String> artistaComboBox2;
    private javax.swing.JTextField cancionField;
    private javax.swing.JTextField codigoField;
    private javax.swing.JButton comCatalogo;
    private javax.swing.JButton creaCatalogo;
    private javax.swing.JComboBox<String> discoComboBox1;
    private javax.swing.JComboBox<String> discoComboBox2;
    private javax.swing.JTextField discoField;
    private javax.swing.JTextField dniField;
    private javax.swing.JTextField duracionField;
    private javax.swing.JButton exportDatos;
    private javax.swing.JFormattedTextField formatPrecioField;
    private javax.swing.JFormattedTextField formattedPrecioCatalogo;
    private javax.swing.JButton genReport;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listaDiscosCatalogo;
    private javax.swing.JTextField nacionalidadField;
    private javax.swing.JTextField nombreCatalogoField;
    private javax.swing.JSpinner numeroSpiner;
    private javax.swing.JButton regArtistButton;
    private javax.swing.JButton regCancionButton;
    private javax.swing.JButton regDiscoButton;
    private javax.swing.JButton removerDiscoCatalogo;
    private javax.swing.JTextArea showData;
    private javax.swing.JSpinner spinStock;
    private javax.swing.JSpinner stockCatalogoSpinner;
    // End of variables declaration//GEN-END:variables
}
